apiVersion: v1
kind: ConfigMap
metadata:
  annotations: {}
  name: nginx-conf-cm
  namespace: blue
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections 10240;
    }
    http {
      server {
        listen 8080;
        add_header Access-Control-Allow-Origin *;
        location / {
          default_type text/plain;
          return 200 "Blue App 1 $server_name\n$remote_addr:$remote_port --> $server_addr:$server_port\nHost: $http_host\nX-Forwarded-For: $http_x_forwarded_for\nX-Custom-Header: $http_x_custom_header\n";
        }
        location /flag {
            set $target_url http://10.1.1.4/$remote_addr-$remote_port/$server_addr-$server_port;
            proxy_pass $target_url;

            proxy_set_header Host 'blue.demo.net';
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
    }



