apiVersion: "k8s.f5net.com/v1"
kind: F5SPKVlan
metadata:
  name: blue-vlan
spec:
  name:  blue-vlan
  interfaces:
    - "1.1"
  tag: 202
  selfip_v4s:
    - 10.2.202.201
    - 10.2.202.202
    - 10.2.202.203
  prefixlen_v4: 24
  auto_lasthop: "AUTO_LASTHOP_ENABLED"
