---
apiVersion: k8s.f5net.com/v3
kind: F5SPKEgress
metadata:
  name: red-egress
spec:
  snatType: SRC_TRANS_SNATPOOL
  egressSnatpool: red-snat
  pseudoCNIConfig:
    namespaces:
      - red
    appPodInterface: eth0
    vxlan:
      create: true
      tmmInterfaceName: internal-vlan
      key: 100
