# BZID 1967881
# additional FLO values to apply when using Production JWT 
# the default values use the test endpoint

# helm upgrade flo oci://repo.f5.com/charts/f5-lifecycle-operator --reuse-values -f flo-values-bz1967881.yaml -n f5-bnk

# additionally, a custom JWKS cpcl-key-cm must be applied after FLO is upgraded.
# kubectl apply -f https://clouddocs.f5.com/bigip-next-for-kubernetes/2.0.0-GA/cpcl-key.yaml -n f5-utils

license:
  teemCertUrl: https://product.apis.f5.com/ee/v1
  teemEntitlementUrl: https://product-s.apis.f5.com/ee/v1
  teemInitialConfigUrl: https://product-s.apis.f5.com/ee/v1