{
 "title": "F5 BNK Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "F5 Ingress Disk IO",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(f5_ingress_system_disk_io{}[$__rate_interval])",
       "legendFormat": "{{device}}-{{direction}}"
      }
     ]
    },
    {
     "title": "F5 Ingress Disk Operation Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(f5_ingress_system_disk_operation_time{}[$__rate_interval])",
       "legendFormat": "{{device}}-{{direction}}"
      }
     ]
    },
    {
     "title": "F5 Ingress System CPU Time(Idle)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 12, "y": 1 },
     "targets": [
      { "expr": "f5_ingress_system_cpu_time{}", "legendFormat": "{{cpu}}" }
     ]
    },
    {
     "title": "F5 Ingress System Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 17, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "f5_ingress_system_memory_usage{}"
      }
     ]
    }
   ]
  },
  {
   "title": "TMM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "F5 TMM CPU Usage 15 mins",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "f5_tmm_tmm_stat_0_cpu_usage_15mins{}",
       "legendFormat": "{{tmmID}}-{{name}}-{{column}}"
      },
      {
       "expr": "f5_tmm_tmm_stat_2_cpu_usage_15mins{}",
       "legendFormat": "{{tmmID}}-{{name}}-{{column}}"
      }
     ]
    },
    {
     "title": "F5 TMM System Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 5, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "f5_tmm_tmm_stat_0_memory_used{}",
       "legendFormat": "{{tmmID}}-{{name}}-{{column}}"
      },
      {
       "expr": "f5_tmm_tmm_stat_2_memory_total{}",
       "legendFormat": "{{tmmID}}-{{name}}-{{column}}"
      }
     ]
    },
    {
     "title": "F5 TMM Interface 1.1 Packets In/Out",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 10, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "f5_tmm_interface_stat_1_1_counters_pkts_in{}",
       "legendFormat": "{{tmmID}}-{{name}}-{{column}}"
      },
      {
       "expr": "f5_tmm_interface_stat_1_1_counters_pkts_out{}",
       "legendFormat": "{{tmmID}}-{{name}}-{{column}}"
      }
     ]
    },
    {
     "title": "F5 TMM Interface 1.1 Bytes In/Out",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 15, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "f5_tmm_interface_stat_1_1_counters_bytes_in{}",
       "legendFormat": "{{tmmID}}-{{name}}-{{column}}"
      },
      {
       "expr": "f5_tmm_interface_stat_1_1_counters_bytes_out{}",
       "legendFormat": "{{tmmID}}-{{name}}-{{column}}"
      }
     ]
    },
    {
     "title": "F5 TMM Network Bytes In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "f5_tmm_tmm_stat_0_server_side_traffic_bytes_out{}",
       "legendFormat": "{{tmmID}}-{{name}}-{{column}}"
      },
      {
       "expr": "f5_tmm_tmm_stat_2_server_side_traffic_bytes_in{}",
       "legendFormat": "{{tmmID}}-{{name}}-{{column}}"
      }
     ]
    },
    {
     "title": "F5 TMM Network Packets In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "f5_tmm_tmm_stat_0_server_side_traffic_pkts_out{}",
       "legendFormat": "{{tmmID}}-{{name}}-{{column}}"
      },
      {
       "expr": "f5_tmm_tmm_stat_2_server_side_traffic_pkts_in{}",
       "legendFormat": "{{tmmID}}-{{name}}-{{column}}"
      }
     ]
    },
    {
     "title": "F5 TMM Interface 1.2 Bytes In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "f5_tmm_interface_stat_1_2_counters_bytes_in{}",
       "legendFormat": "{{tmmID}}-{{column}}"
      },
      {
       "expr": "f5_tmm_interface_stat_1_2_counters_bytes_out{}",
       "legendFormat": "{{tmmID}}-{{column}}"
      }
     ]
    },
    {
     "title": "F5 TMM Interface 1.2 Pkts In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 15, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "f5_tmm_interface_stat_1_2_counters_pkts_in{}",
       "legendFormat": "{{tmmID}}-{{column}}"
      },
      {
       "expr": "f5_tmm_interface_stat_1_2_counters_pkts_out{}",
       "legendFormat": "{{tmmID}}-{{column}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ACL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "ACL Rejected",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "f5_tmm_fw_context_stat_1_packets_reject{}",
       "legendFormat": "{{tmmID}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Blue Tenant",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual Server Packets In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "f5_tmm_virtual_server_stat_blue_gatewayapi_l4_tcp_app_0_virtual_server_serverside_pkts_out{}",
       "legendFormat": "{{tmmID}}-{{column}}"
      },
      {
       "expr": "f5_tmm_virtual_server_stat_blue_gatewayapi_l4_tcp_app_0_virtual_server_serverside_pkts_in{}",
       "legendFormat": "{{tmmID}}-{{column}}"
      }
     ]
    },
    {
     "title": "Virtual Server Client Packets In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 5, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "f5_tmm_virtual_server_stat_blue_gatewayapi_l4_tcp_app_0_virtual_server_clientside_pkts_in{}",
       "legendFormat": "{{tmmID}}-{{column}}"
      },
      {
       "expr": "f5_tmm_virtual_server_stat_blue_gatewayapi_l4_tcp_app_0_virtual_server_clientside_pkts_out{}",
       "legendFormat": "{{tmmID}}-{{column}}"
      }
     ]
    },
    {
     "title": "Virtual Server Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 11, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "f5_tmm_virtual_server_stat_blue_gatewayapi_l4_tcp_app_0_virtual_server_clientside_cur_conns{}",
       "legendFormat": "{{tmmID}}-{{column}}"
      },
      {
       "expr": "f5_tmm_virtual_server_stat_blue_gatewayapi_l4_tcp_app_0_virtual_server_clientside_tot_conns{}",
       "legendFormat": "{{namespace}}-{{tmmID}}-{{column}}"
      }
     ]
    },
    {
     "title": "Virtual Server Bytes In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 17, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "f5_tmm_virtual_server_stat_blue_gatewayapi_l4_tcp_app_0_virtual_server_serverside_bytes_in{}",
       "legendFormat": "{{tmmID}}-{{column}}"
      },
      {
       "expr": "f5_tmm_virtual_server_stat_blue_gatewayapi_l4_tcp_app_0_virtual_server_serverside_bytes_out{}",
       "legendFormat": "{{tmmID}}-{{column}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Red Tenant",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual Server Packets In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "f5_tmm_virtual_server_stat_red_gatewayapi_l4_tcp_app_0_virtual_server_serverside_pkts_out{}",
       "legendFormat": "{{tmmID}}-{{column}}"
      },
      {
       "expr": "f5_tmm_virtual_server_stat_red_gatewayapi_l4_tcp_app_0_virtual_server_serverside_pkts_in{}",
       "legendFormat": "{{tmmID}}-{{column}}"
      }
     ]
    },
    {
     "title": "Virtual Server Client Packets In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 5, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "f5_tmm_virtual_server_stat_red_gatewayapi_l4_tcp_app_0_virtual_server_clientside_pkts_in{}",
       "legendFormat": "{{tmmID}}-{{column}}"
      },
      {
       "expr": "f5_tmm_virtual_server_stat_red_gatewayapi_l4_tcp_app_0_virtual_server_clientside_pkts_out{}",
       "legendFormat": "{{tmmID}}-{{column}}"
      }
     ]
    },
    {
     "title": "Virtual Server Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 11, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "f5_tmm_virtual_server_stat_red_gatewayapi_l4_tcp_app_0_virtual_server_clientside_cur_conns{}",
       "legendFormat": "{{tmmID}}-{{column}}"
      },
      {
       "expr": "f5_tmm_virtual_server_stat_red_gatewayapi_l4_tcp_app_0_virtual_server_clientside_tot_conns{}",
       "legendFormat": "{{namespace}}-{{tmmID}}-{{column}}"
      }
     ]
    },
    {
     "title": "Virtual Server Bytes In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 17, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "f5_tmm_virtual_server_stat_red_gatewayapi_l4_tcp_app_0_virtual_server_serverside_bytes_in{}",
       "legendFormat": "{{tmmID}}-{{column}}"
      },
      {
       "expr": "f5_tmm_virtual_server_stat_red_gatewayapi_l4_tcp_app_0_virtual_server_serverside_bytes_out{}",
       "legendFormat": "{{tmmID}}-{{column}}"
      }
     ]
    }
   ]
  }
 ]
}