{
 "title": "F5 BNK Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "TMM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "F5 TMM CPU Usage 15 mins",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "f5_tmm_f5_tmm_cpu_utilization_15mins_per_10_2{}",
       "legendFormat": "{{tmmID}}-{{name}}-{{column}}"
      },
      {
       "expr": "f5_tmm_tmm_stat_2_cpu_usage_15mins{}",
       "legendFormat": "{{tmmID}}-{{name}}-{{column}}"
      }
     ]
    },
    {
     "title": "F5 TMM System Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 5, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "f5_tmm_f5_tmm_memory_usage_bytes{}",
       "legendFormat": "{{tmmID}}-{{name}}-{{column}}"
      },
      {
       "expr": "f5_tmm_tmm_stat_2_memory_total{}",
       "legendFormat": "{{tmmID}}-{{name}}-{{column}}"
      }
     ]
    },
    {
     "title": "F5 TMM Interface Bytes In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "f5_tmm_f5_l3_interface_recieved_octets_total{}",
       "legendFormat": "{{tmmID}}-{{column}}"
      },
      {
       "expr": "f5_tmm_f5_l3_interface_transmitted_octets_total{}",
       "legendFormat": "{{tmmID}}-{{column}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Blue Tenant",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual Server Packets In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "f5_tmm_f5_virtual_server_serverside_transmitted_packets_total{f5_virtual_server_name=\"blue-my-http-gateway-172.16.202.100-http-listener-vs\"}",
       "legendFormat": "{{tmmID}}-{{column}}"
      },
      {
       "expr": "f5_tmm_f5_virtual_server_serverside_received_packets_total{f5_virtual_server_name=\"blue-my-http-gateway-172.16.202.100-http-listener-vs\"}",
       "legendFormat": "{{tmmID}}-{{column}}"
      }
     ]
    },
    {
     "title": "Virtual Server Client Packets In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 5, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "f5_tmm_f5_virtual_server_clientside_received_packets_total{f5_virtual_server_name=\"blue-my-http-gateway-172.16.202.100-http-listener-vs\"}",
       "legendFormat": "{{tmmID}}-{{column}}"
      },
      {
       "expr": "f5_tmm_f5_virtual_server_clientside_transmitted_packets_total{f5_virtual_server_name=\"blue-my-http-gateway-172.16.202.100-http-listener-vs\"}",
       "legendFormat": "{{tmmID}}-{{column}}"
      }
     ]
    },
    {
     "title": "Virtual Server Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 11, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "f5_tmm_f5_virtual_server_clientside_connections_current{f5_virtual_server_name=\"blue-my-http-gateway-172.16.202.100-http-listener-vs\"}",
       "legendFormat": "{{tmmID}}-{{column}}"
      },
      {
       "expr": "f5_tmm_f5_virtual_server_clientside_connections_total{f5_virtual_server_name=\"blue-my-http-gateway-172.16.202.100-http-listener-vs\"}",
       "legendFormat": "{{namespace}}-{{tmmID}}-{{column}}"
      }
     ]
    },
    {
     "title": "Virtual Server Bytes In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 17, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "f5_tmm_f5_virtual_server_serverside_received_bytes_total{f5_virtual_server_name=\"blue-my-http-gateway-172.16.202.100-http-listener-vs\"}",
       "legendFormat": "{{tmmID}}-{{column}}"
      },
      {
       "expr": "f5_tmm_f5_virtual_server_serverside_transmitted_bytes_total{f5_virtual_server_name=\"blue-my-http-gateway-172.16.202.100-http-listener-vs\"}",
       "legendFormat": "{{tmmID}}-{{column}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Red Tenant",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual Server Packets In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "f5_tmm_f5_virtual_server_serverside_transmitted_packets_total{f5_virtual_server_name=\"red-my-tcp-gateway-172.16.201.100-tcp-listener-vs\"}",
       "legendFormat": "{{tmmID}}-{{column}}"
      },
      {
       "expr": "f5_tmm_f5_virtual_server_serverside_received_packets_total{f5_virtual_server_name=\"red-my-tcp-gateway-172.16.201.100-tcp-listener-vs\"}",
       "legendFormat": "{{tmmID}}-{{column}}"
      }
     ]
    },
    {
     "title": "Virtual Server Client Packets In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 5, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "f5_tmm_f5_virtual_server_clientside_received_packets_total{f5_virtual_server_name=\"red-my-tcp-gateway-172.16.201.100-tcp-listener-vs\"}",
       "legendFormat": "{{tmmID}}-{{column}}"
      },
      {
       "expr": "f5_tmm_f5_virtual_server_clientside_transmitted_packets_total{f5_virtual_server_name=\"red-my-tcp-gateway-172.16.201.100-tcp-listener-vs\"}",
       "legendFormat": "{{tmmID}}-{{column}}"
      }
     ]
    },
    {
     "title": "Virtual Server Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 11, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "f5_tmm_f5_virtual_server_clientside_connections_current{f5_virtual_server_name=\"red-my-tcp-gateway-172.16.201.100-tcp-listener-vs\"}",
       "legendFormat": "{{tmmID}}-{{column}}"
      },
      {
       "expr": "f5_tmm_f5_virtual_server_clientside_connections_total{f5_virtual_server_name=\"red-my-tcp-gateway-172.16.201.100-tcp-listener-vs\"}",
       "legendFormat": "{{namespace}}-{{tmmID}}-{{column}}"
      }
     ]
    },
    {
     "title": "Virtual Server Bytes In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 17, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "f5_tmm_f5_virtual_server_serverside_received_bytes_total{f5_virtual_server_name=\"red-my-tcp-gateway-172.16.201.100-tcp-listener-vs\"}",
       "legendFormat": "{{tmmID}}-{{column}}"
      },
      {
       "expr": "f5_tmm_f5_virtual_server_serverside_transmitted_bytes_total{f5_virtual_server_name=\"red-my-tcp-gateway-172.16.201.100-tcp-listener-vs\"}",
       "legendFormat": "{{tmmID}}-{{column}}"
      }
     ]
    }
   ]
  }
 ]
}