# updated for v2.1 to include BNKSecPolicy
apiVersion: "k8s.f5net.com/v1"
kind: F5BigFwPolicy
metadata:
  name: firewallpolicy-gateway
  # firewall policy must be applied in same namespace as resource specified in targetRefs
spec:
  rule:
  - name: sc-rule-tcp-ingress-1
    ipProtocol: any
    source:
      addresses:
      - 10.2.30.101/32
    logging: true
    action: drop
---
apiVersion: "gateway.k8s.f5net.com/v1alpha1"
kind: BNKSecPolicy
metadata:
  name: secpolicy-gateway
spec:
  extensionRefs:
  - kind: F5BigFwPolicy
    name: firewallpolicy-gateway
    group: k8s.f5net.com
  targetRefs:
  - kind: Gateway
    name: my-tcp-gateway
    group: gateway.networking.k8s.io
    sectionName: "tcp-listener"

